### ISSUE TITLE
jruby 1.7.13 support?

### ISSUE THREAD

**Issue by mooreniemi** [glejeune/Ruby-Graphviz#104]
/Users/amooreniemi/.rvm/gems/jruby-1.7.13/gems/ruby-graphviz-1.2.1/lib/graphviz/utils.rb:61:in `output_from_command': Error from ["/usr/local/bin/dot", "-q1", "-Tpng", "-o/Users/amooreniemi/work repos/zipcar-rails-core/gem_graph.png", "/var/folders/fh/hd6ktyp11mg2gft_gcph47sjt21mtb/T/graphviz.rb20150320-16670-e641zp"]: (RuntimeError)
Error: dot: can't open {}

	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13/gems/ruby-graphviz-1.2.1/lib/graphviz.rb:600:in `output'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/lib/bundler/graph.rb:156:in `run'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/lib/bundler/graph.rb:25:in `viz'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/lib/bundler/cli/viz.rb:12:in `run'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/lib/bundler/cli.rb:321:in `viz'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/lib/bundler/vendor/thor/command.rb:27:in `run'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/lib/bundler/vendor/thor.rb:363:in `dispatch'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/lib/bundler/vendor/thor/base.rb:440:in `start'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/lib/bundler/cli.rb:9:in `start'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/bin/bundle:20:in `(root)'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/gems/bundler-1.7.3/bin/bundle:18:in `(root)'
	from org/jruby/RubyKernel.java:1081:in `load'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13@global/bin/bundle:1:in `(root)'
	from org/jruby/RubyKernel.java:1101:in `eval'
	from /Users/amooreniemi/.rvm/gems/jruby-1.7.13/bin/jruby_executable_hooks:15:in `(root)'

**Comment by mooreniemi** [comment]
still broken

**Comment by mooreniemi** [comment]
i pry'd into:

def output_and_errors_from_command(cmd) #:nodoc:
      unless defined? Open3
        begin
          require 'open3'
          require 'win32/open3'
        rescue LoadError
        end
      end
      begin
            require 'pry'
    binding.pry
        out, err, status = Open3.capture3(*cmd, :binmode => true)
        [out, err, status.exitstatus]
      rescue NotImplementedError, NoMethodError
        IO.popen( *cmd ) do |stdout|
          stdout.binmode
          [stdout.read, nil, nil]
        end
      end
    end

and found the command being constructed ran without errors when i ran it in my console directly
